# Glossary terms for tooltips
RSI:
  term: "RSI (Relative Strength Index)"
  definition: "Momentum indicator; >70 overbought, <30 oversold. Default period 14."
SMA:
  term: "SMA (Simple Moving Average)"
  definition: "Average closing price over N days; equal weights."
EMA:
  term: "EMA (Exponential Moving Average)"
  definition: "Moving average that weights recent prices more."
MACD:
  term: "MACD"
  definition: "Difference of fast and slow EMAs with a signal line."
ATR:
  term: "ATR (Average True Range)"
  definition: "Volatility measure used for stops and sizing."
Bollinger Bands:
  term: "Bollinger Bands"
  definition: "Bands at ±K standard deviations from a moving average."
Sharpe Ratio:
  term: "Sharpe Ratio"
  definition: "Return per unit of volatility; higher is better."
Sortino Ratio:
  term: "Sortino Ratio"
  definition: "Like Sharpe but uses downside-only volatility."
Max Drawdown:
  term: "Max Drawdown"
  definition: "Largest peak-to-trough decline in equity curve."
Beta:
  term: "Beta"
  definition: "Sensitivity to a benchmark (or BTC proxy for BTC-linked equities)."
VIX:
  term: "VIX"
  definition: "Implied volatility of S&P 500 options; higher = more market stress."
DXY:
  term: "DXY (US Dollar Index)"
  definition: "USD strength versus a basket; strong USD can pressure risk assets."
UST10Y:
  term: "UST10Y (10-year Treasury yield)"
  definition: "Benchmark interest rate; rising yields tighten financial conditions."
Calibration:
  term: "Calibration"
  definition: "Aligning model probabilities with observed frequencies."
Regime:
  term: "Regime"
  definition: "Detected market state (e.g., high vol vs low vol) used to adjust decisions."
