name: Backtest Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run baseline backtest
        run: |
          python backend/app/backtest_baseline.py

      - name: Upload backtest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-smoke-artifacts
          path: |
            data/public/backtest_baseline.json
            data/public/backtest_equity.json
            data/public/backtest_rolling.json
            data/public/backtest_monthly.json

