name: Frontend Pages Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docs/**'
      - 'configs/glossary.yaml'
      - '.github/workflows/pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install deps
        run: |
          cd frontend
          npm ci

      - name: Copy public data for static site
        run: |
          mkdir -p frontend/public/data/public
          mkdir -p frontend/public/configs
          cp -r data/public/*.json frontend/public/data/public/ || true
          cp configs/glossary.yaml frontend/public/configs/glossary.yaml || true
          cp configs/frontend.json frontend/public/configs/frontend.json || true
          cp configs/terminology.json frontend/public/configs/terminology.json || true
          mkdir -p frontend/public/docs
          cp docs/BACKTEST.md frontend/public/docs/BACKTEST.md || true
          cp docs/ALGORITHM.md frontend/public/docs/ALGORITHM.md || true
          cp docs/ALGORITHM_ESSAY.md frontend/public/docs/ALGORITHM_ESSAY.md || true

      - name: Build static export
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=/mstr-advisor" >> $GITHUB_ENV
          cd frontend
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


